
// File generated by Go version U-2022.12#33f3808fcb#221128, Sun Sep 15 20:05:03 2024
// Copyright 2014-2022 Synopsys, Inc. All rights reserved.
// go -I../lib -F -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -Verilog -otrv32p5x_vlog -cgo_options.cfg -Itrv32p5x_vlog/tmp_pdg -updg -updg_controller trv32p5x




// File generated by pdg version U-2022.12#33f3808fcb#221128
// Copyright 2014-2022 Synopsys, Inc. All rights reserved.
// pdg -I../lib -D__go__ -Verilog -cgo_options.cfg -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 +wtrv32p5x_vlog/tmp_pdg trv32p5x


task w32_add_w32_w32
  ( output reg signed [31:0] result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : w32_add_w32_w32_task
    result = a + b;
  end
endtask

task w32_sub_w32_w32
  ( output reg signed [31:0] result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : w32_sub_w32_w32_task
    result = a - b;
  end
endtask

task w32_slt_w32_w32
  ( output reg signed [31:0] result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : w32_slt_w32_w32_task
    result = $signed({{31{1'b0}}, a < b});
  end
endtask

task w32_sltu_w32_w32
  ( output reg signed [31:0] result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : w32_sltu_w32_w32_task
    result = $signed({{31{1'b0}}, $unsigned(a) < $unsigned(b)});
  end
endtask

task w32_seq0_w32
  ( output reg signed [31:0] result,
    input      signed [31:0] a
  );
  begin : w32_seq0_w32_task
    result = $signed({{31{1'b0}}, a == 32'sh0});
  end
endtask

task w32_sne0_w32
  ( output reg signed [31:0] result,
    input      signed [31:0] a
  );
  begin : w32_sne0_w32_task
    result = $signed({{31{1'b0}}, a != 32'sh0});
  end
endtask

task w32_mul_w32_w32
  ( output reg signed [31:0] result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : w32_mul_w32_w32_task
    reg signed [63:0] rtrn;
    rtrn = a * b;
    result = $signed(rtrn[31:0]);
  end
endtask

task w32_mulh_w32_w32
  ( output reg signed [31:0] result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : w32_mulh_w32_w32_task
    reg signed [63:0] p;
    p = a * b;
    result = $signed(p[63 : 32]);
  end
endtask

task w32_mulhsu_w32_w32
  ( output reg signed [31:0] result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : w32_mulhsu_w32_w32_task
    reg signed [63:0] p;
    p = a * $signed({1'b0, $unsigned(b)});
    result = $signed(p[63 : 32]);
  end
endtask

task w32_mulhu_w32_w32
  ( output reg signed [31:0] result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : w32_mulhu_w32_w32_task
    reg        [63:0] p;
    reg signed [63:0] p_0;
    p = $unsigned(a) * $unsigned(b);
    p_0 = $signed(p);
    result = $signed(p_0[63 : 32]);
  end
endtask

task w32_band_w32_w32
  ( output reg signed [31:0] result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : w32_band_w32_w32_task
    result = a & b;
  end
endtask

task w32_bor_w32_w32
  ( output reg signed [31:0] result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : w32_bor_w32_w32_task
    result = a | b;
  end
endtask

task w32_bxor_w32_w32
  ( output reg signed [31:0] result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : w32_bxor_w32_w32_task
    result = a ^ b;
  end
endtask

task bool_eq_w32_w32
  ( output reg               result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : bool_eq_w32_w32_task
    result = a == b;
  end
endtask

task bool_ne_w32_w32
  ( output reg               result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : bool_ne_w32_w32_task
    result = a != b;
  end
endtask

task bool_lt_w32_w32
  ( output reg               result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : bool_lt_w32_w32_task
    result = a < b;
  end
endtask

task bool_ge_w32_w32
  ( output reg               result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : bool_ge_w32_w32_task
    result = a >= b;
  end
endtask

task bool_ltu_w32_w32
  ( output reg               result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : bool_ltu_w32_w32_task
    result = $unsigned(a) < $unsigned(b);
  end
endtask

task bool_geu_w32_w32
  ( output reg               result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : bool_geu_w32_w32_task
    result = $unsigned(a) >= $unsigned(b);
  end
endtask

task w32_sra_w32_w32
  ( output reg signed [31:0] result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : w32_sra_w32_w32_task
    result = (a >>> $unsigned($signed(b[4 : 0])));
  end
endtask

task w32_sll_w32_w32
  ( output reg signed [31:0] result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : w32_sll_w32_w32_task
    reg        [31:0] rtrn;
    rtrn = $unsigned(a) << $unsigned($signed(b[4 : 0]));
    result = $signed(rtrn);
  end
endtask

task w32_srl_w32_w32
  ( output reg signed [31:0] result,
    input      signed [31:0] a,
    input      signed [31:0] b
  );
  begin : w32_srl_w32_w32_task
    reg        [31:0] rtrn;
    rtrn = ($unsigned(a) >> $unsigned($signed(b[4 : 0])));
    result = $signed(rtrn);
  end
endtask

task w32_sext_w08
  ( output reg signed [31:0] result,
    input      signed  [7:0] a
  );
  begin : w32_sext_w08_task
    result = $signed({{24{a[7]}}, a});
  end
endtask

task w32_zext_w08
  ( output reg signed [31:0] result,
    input      signed  [7:0] a
  );
  begin : w32_zext_w08_task
    result = $signed({{24{1'b0}}, $unsigned(a)});
  end
endtask

task w32_sext_w16
  ( output reg signed [31:0] result,
    input      signed [15:0] a
  );
  begin : w32_sext_w16_task
    result = $signed({{16{a[15]}}, a});
  end
endtask

task w32_zext_w16
  ( output reg signed [31:0] result,
    input      signed [15:0] a
  );
  begin : w32_zext_w16_task
    result = $signed({{16{1'b0}}, $unsigned(a)});
  end
endtask

task void_nop
  ( );
  begin : void_nop_task
  end
endtask

task addr_incr1_addr
  ( output reg        [31:0] result,
    input             [31:0] a
  );
  begin : addr_incr1_addr_task
    result = a + 32'h1;
  end
endtask

task addr_incr8_addr
  ( output reg        [31:0] result,
    input             [31:0] a
  );
  begin : addr_incr8_addr_task
    result = a + 32'h8;
  end
endtask

task void_mul_hw_w32_w32_t2u_w32_w32
  ( input      signed [31:0] opa,
    input      signed [31:0] opb,
    input              [1:0] mode,
    output reg signed [31:0] pl,
    output reg signed [31:0] ph
  );
  begin : void_mul_hw_w32_w32_t2u_w32_w32_task
    reg signed [32:0] a;
    reg signed [32:0] b;
    reg signed [65:0] r;
    a = $signed({mode[1] & opa[31] , $unsigned(opa)});
    b = $signed({mode[0] & opb[31] , $unsigned(opb)});
    r = a * b;
    pl = $signed(r[31 : 0]);
    ph = $signed(r[63 : 32]);
  end
endtask

task t2u_inc1_t2u
  ( output reg         [1:0] result,
    input              [1:0] a
  );
  begin : t2u_inc1_t2u_task
    result = a + 2'h1;
  end
endtask

task void_round_w08_w64_w64_w64_w64_w64_w64_w64_w64_w64_w64
  ( input      signed  [7:0] C,
    input             [63:0] x0_i,
    input             [63:0] x1_i,
    input             [63:0] x2_i,
    input             [63:0] x3_i,
    input             [63:0] x4_i,
    output reg        [63:0] x0_o,
    output reg        [63:0] x1_o,
    output reg        [63:0] x2_o,
    output reg        [63:0] x3_o,
    output reg        [63:0] x4_o
  );
  begin : void_round_w08_w64_w64_w64_w64_w64_w64_w64_w64_w64_w64_task
    reg        [63:0] x0;
    reg        [63:0] x1;
    reg        [63:0] x2;
    reg        [63:0] x3;
    reg        [63:0] x4;
    reg        [63:0] xtemp;
    reg        [63:0] C64;
    reg        [63:0] x2_0;
    reg        [63:0] x0_0;
    reg        [63:0] x4_0;
    reg        [63:0] x2_1;
    reg        [63:0] x0_1;
    reg        [63:0] x2_2;
    reg        [63:0] x4_1;
    reg        [63:0] x1_0;
    reg        [63:0] x3_0;
    reg        [63:0] x1_1;
    reg        [63:0] x3_1;
    reg        [63:0] x0_2;
    reg        [63:0] x2_3;
    reg        [63:0] x0_3;
    reg        [63:0] x0_4;
    reg        [63:0] x0_5;
    reg        [63:0] x0_6;
    reg        [63:0] x0_7;
    reg        [63:0] x1_2;
    reg        [63:0] x1_3;
    reg        [63:0] x1_4;
    reg        [63:0] x1_5;
    reg        [63:0] x1_6;
    reg        [63:0] x2_4;
    reg        [63:0] x2_5;
    reg        [63:0] x2_6;
    reg        [63:0] x2_7;
    reg        [63:0] x2_8;
    reg        [63:0] x3_2;
    reg        [63:0] x3_3;
    reg        [63:0] x3_4;
    reg        [63:0] x3_5;
    reg        [63:0] x3_6;
    reg        [63:0] x4_2;
    reg        [63:0] x4_3;
    reg        [63:0] x4_4;
    reg        [63:0] x4_5;
    reg        [63:0] x4_6;
    x0 = x0_i;
    x1 = x1_i;
    x2 = x2_i;
    x3 = x3_i;
    x4 = x4_i;
    C64 = 64'h0;
    C64[7 : 0] = $unsigned(C);
    x2_0 = x2;
    x2 = x2_0 ^ C64;
    x0_0 = x0;
    x0 = x0_0 ^ x4;
    x4_0 = x4;
    x4 = x4_0 ^ x3;
    x2_1 = x2;
    x2 = x2_1 ^ x1;
    xtemp = x0 & ~x4;
    x0_1 = x0;
    x0 = x0_1 ^ x2 & ~x1;
    x2_2 = x2;
    x2 = x2_2 ^ x4 & ~x3;
    x4_1 = x4;
    x4 = x4_1 ^ x1 & ~x0;
    x1_0 = x1;
    x1 = x1_0 ^ x3 & ~x2;
    x3_0 = x3;
    x3 = x3_0 ^ xtemp;
    x1_1 = x1;
    x1 = x1_1 ^ x0;
    x3_1 = x3;
    x3 = x3_1 ^ x2;
    x0_2 = x0;
    x0 = x0_2 ^ x4;
    x2_3 = x2;
    x2 = ~x2_3;
    x0_3 = (x0 >> 5'h13);
    x0_4 = x0 << 6'h2D;
    x0_5 = (x0 >> 5'h1C);
    x0_6 = x0 << 6'h24;
    x0_7 = x0;
    x0 = x0_7 ^ (x0_3 ^ x0_4 ^ x0_5 ^ x0_6);
    x1_2 = (x1 >> 6'h3D);
    x1_3 = x1 << 2'h3;
    x1_4 = (x1 >> 6'h27);
    x1_5 = x1 << 5'h19;
    x1_6 = x1;
    x1 = x1_6 ^ (x1_2 ^ x1_3 ^ x1_4 ^ x1_5);
    x2_4 = (x2 >> 1'b1);
    x2_5 = x2 << 6'h3F;
    x2_6 = (x2 >> 3'h6);
    x2_7 = x2 << 6'h3A;
    x2_8 = x2;
    x2 = x2_8 ^ (x2_4 ^ x2_5 ^ x2_6 ^ x2_7);
    x3_2 = (x3 >> 4'hA);
    x3_3 = x3 << 6'h36;
    x3_4 = (x3 >> 5'h11);
    x3_5 = x3 << 6'h2F;
    x3_6 = x3;
    x3 = x3_6 ^ (x3_2 ^ x3_3 ^ x3_4 ^ x3_5);
    x4_2 = (x4 >> 3'h7);
    x4_3 = x4 << 6'h39;
    x4_4 = (x4 >> 6'h29);
    x4_5 = x4 << 5'h17;
    x4_6 = x4;
    x4 = x4_6 ^ (x4_2 ^ x4_3 ^ x4_4 ^ x4_5);
    x0_o = x0;
    x1_o = x1;
    x2_o = x2;
    x3_o = x3;
    x4_o = x4;
  end
endtask

