
// File generated by Go version U-2022.12#33f3808fcb#221128, Sun Sep 15 20:05:03 2024
// Copyright 2014-2022 Synopsys, Inc. All rights reserved.
// go -I../lib -F -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -Verilog -otrv32p5x_vlog -cgo_options.cfg -Itrv32p5x_vlog/tmp_pdg -updg -updg_controller trv32p5x



`timescale 1ns/1ps

// module reg_S : reg_S
module reg_S
  // synopsys translate_off
  #(parameter reg_log = 1'b1)
  // synopsys translate_on
  ( input             clock,
    input             ohe_selector_WB,
    input             ohe_selector_EX,
    input       [2:0] __S_s_r_raddr_in, // t3u
    input       [2:0] __S_s_w_waddr_in, // t3u
    input      [63:0] s00w_in, // w64
    input      [63:0] s01w_in, // w64
    input      [63:0] s02w_in, // w64
    input      [63:0] s03w_in, // w64
    input      [63:0] s04w_in, // w64
    input      [63:0] s_w_in, // w64
    output reg [63:0] s00r_out, // w64
    output reg [63:0] s01r_out, // w64
    output reg [63:0] s02r_out, // w64
    output reg [63:0] s03r_out, // w64
    output reg [63:0] s04r_out, // w64
    output reg [63:0] s_r_out // w64
  );


  reg [63:0] reg_val[0:4];

  // synopsys translate_off

  reg [4:0] reg_write_log;

  always @ (negedge clock)
  begin : p_reg_S_log

    integer k;

    if (reg_log)
    begin
      for (k = 0; k <= 4; k = k + 1)
      begin
        if (reg_write_log[k] === 1'b1)
        begin
          $fdisplay(trv32p5x.inst_reg_PC.log_file, "S[%0d] = %h", k, reg_val[k]);
        end
      end
    end
  end
  // synopsys translate_on

  always @ (*)
  begin : p_read_reg_S

    // s00r_out = 64'h0;
    // s01r_out = 64'h0;
    // s02r_out = 64'h0;
    // s03r_out = 64'h0;
    // s04r_out = 64'h0;
    // s_r_out = 64'h0;

    // (s00r_rd_S00_EX, s01r_rd_S01_EX, s02r_rd_S02_EX, s03r_rd_S03_EX, s04r_rd_S04_EX)
    // [userext.n:167]
    s00r_out = reg_val[0];
    // [userext.n:167]
    s01r_out = reg_val[1];
    // [userext.n:167]
    s02r_out = reg_val[2];
    // [userext.n:167]
    s03r_out = reg_val[3];
    // [userext.n:167]
    s04r_out = reg_val[4];

    // (s_r_rd_S___S_s_r_rad_ID)
    // [userext.n:55]
    s_r_out = reg_val[__S_s_r_raddr_in];

  end

  always @ (posedge clock)
  begin : p_write_reg_S

    // synopsys translate_off
    reg_write_log <= {5{1'b0}};
    // synopsys translate_on

    if (ohe_selector_WB) // (S_wr_s_w___S_s_w_wad_WB)
    begin
      // [userext.n:66]
      // synopsys translate_off
      reg_write_log[__S_s_w_waddr_in] <= 1'b1;
      // synopsys translate_on
      reg_val[__S_s_w_waddr_in] <= s_w_in;
    end

    if (ohe_selector_EX) // (S00_wr_s00w_EX, S01_wr_s01w_EX, S02_wr_s02w_EX, S03_wr_s03w_EX, S04_wr_s04w_EX)
    begin
      // [userext.n:167]
      // synopsys translate_off
      reg_write_log[0] <= 1'b1;
      // synopsys translate_on
      reg_val[0] <= s00w_in;
      // [userext.n:167]
      // synopsys translate_off
      reg_write_log[1] <= 1'b1;
      // synopsys translate_on
      reg_val[1] <= s01w_in;
      // [userext.n:167]
      // synopsys translate_off
      reg_write_log[2] <= 1'b1;
      // synopsys translate_on
      reg_val[2] <= s02w_in;
      // [userext.n:167]
      // synopsys translate_off
      reg_write_log[3] <= 1'b1;
      // synopsys translate_on
      reg_val[3] <= s03w_in;
      // [userext.n:167]
      // synopsys translate_off
      reg_write_log[4] <= 1'b1;
      // synopsys translate_on
      reg_val[4] <= s04w_in;
    end

  end

endmodule
